workspace:
  base: /workspace
  path: .
pipeline:
  build:
    image: flowup/drone-bazel
    pull: true
    cmd:
     - run --define COMMIT_HASH=${DRONE_COMMIT_SHA} //trip/cmd/trip:push
    secrets: [gcr_json_key]
  template-k8s:
    image: flowup/drone-sed
    cmd: "-i 's#latest#${DRONE_COMMIT_SHA}#' infrastructure/shared/*.yaml"
    pull: true
    when:
      event: [push, deployment]
      branch: master
  deploy-backend:
    group: deploy
    image: flowup/drone-kubectl
    cluster: krokomotiva
    zone: europe-west3-b
    project: peto-199916
    cmd: apply -R -f infrastructure/ -n default
    pull: true
    when:
      event: push
      branch: master
    secrets: [gcr_json_key]