// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto.proto

/*
	Package trip is a generated protocol buffer package.

	It is generated from these files:
		proto.proto

	It has these top-level messages:
		Version
*/
package trip

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import core "github.com/gelidus/web-krokomotiva/core"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptorProto, []int{0} }

func (m *Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "trip.Version")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TripService service

type TripServiceClient interface {
	GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Version, error)
	Check(ctx context.Context, in *core.HealthCheckRequest, opts ...grpc.CallOption) (*core.HealthCheckResponse, error)
}

type tripServiceClient struct {
	cc *grpc.ClientConn
}

func NewTripServiceClient(cc *grpc.ClientConn) TripServiceClient {
	return &tripServiceClient{cc}
}

func (c *tripServiceClient) GetVersion(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := grpc.Invoke(ctx, "/trip.TripService/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tripServiceClient) Check(ctx context.Context, in *core.HealthCheckRequest, opts ...grpc.CallOption) (*core.HealthCheckResponse, error) {
	out := new(core.HealthCheckResponse)
	err := grpc.Invoke(ctx, "/trip.TripService/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TripService service

type TripServiceServer interface {
	GetVersion(context.Context, *google_protobuf.Empty) (*Version, error)
	Check(context.Context, *core.HealthCheckRequest) (*core.HealthCheckResponse, error)
}

func RegisterTripServiceServer(s *grpc.Server, srv TripServiceServer) {
	s.RegisterService(&_TripService_serviceDesc, srv)
}

func _TripService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trip.TripService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).GetVersion(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TripService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(core.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TripServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trip.TripService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TripServiceServer).Check(ctx, req.(*core.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TripService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trip.TripService",
	HandlerType: (*TripServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _TripService_GetVersion_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _TripService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

func (m *Version) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Version) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintProto(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	return i, nil
}

func encodeVarintProto(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Version) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovProto(uint64(l))
	}
	return n
}

func sovProto(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozProto(x uint64) (n int) {
	return sovProto(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Version) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProto
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Version: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Version: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProto
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProto
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProto(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthProto
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProto(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProto
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProto
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProto
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthProto
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowProto
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipProto(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthProto = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProto   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("proto.proto", fileDescriptorProto) }

var fileDescriptorProto = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0x3d, 0x4b, 0xc4, 0x30,
	0x1c, 0xc6, 0x8d, 0x9c, 0x6f, 0x39, 0x04, 0xc9, 0x20, 0x77, 0x55, 0x8b, 0xdc, 0xa2, 0x8b, 0x09,
	0xe8, 0x24, 0x38, 0x29, 0x87, 0xce, 0xa7, 0x38, 0xb8, 0xa5, 0xf5, 0x6f, 0x1b, 0xda, 0xe6, 0x1f,
	0x93, 0xb4, 0xe2, 0xea, 0x47, 0xd0, 0xc5, 0x8f, 0xe4, 0x28, 0xf8, 0x05, 0xa4, 0xfa, 0x41, 0xa4,
	0x2f, 0x07, 0x37, 0xb8, 0x84, 0xf0, 0x3c, 0xcf, 0x2f, 0xf9, 0xd1, 0xa1, 0xb1, 0xe8, 0x91, 0xb7,
	0x27, 0x1b, 0x78, 0xab, 0x4c, 0xb0, 0x93, 0x20, 0x26, 0x39, 0x88, 0x36, 0x8b, 0xca, 0x07, 0x01,
	0x85, 0xf1, 0xcf, 0xdd, 0x24, 0x18, 0xc7, 0x68, 0x17, 0xaa, 0x05, 0x3a, 0xd8, 0xed, 0x39, 0x69,
	0x94, 0x90, 0x5a, 0xa3, 0x97, 0x5e, 0xa1, 0x76, 0x5d, 0x3b, 0xd9, 0xa3, 0x6b, 0xb7, 0x60, 0x9d,
	0x42, 0xcd, 0x18, 0x1d, 0x68, 0x59, 0xc0, 0x88, 0xec, 0x93, 0xc3, 0x8d, 0x59, 0x7b, 0x3f, 0x7e,
	0x25, 0x74, 0x78, 0x63, 0x95, 0xb9, 0x06, 0x5b, 0xa9, 0x18, 0xd8, 0x94, 0xd2, 0x4b, 0xf0, 0x73,
	0x62, 0x9b, 0x77, 0x6f, 0xf3, 0xf9, 0xc7, 0x7c, 0xda, 0x38, 0x05, 0x9b, 0xbc, 0x31, 0xe6, 0xfd,
	0x6c, 0xb2, 0xf5, 0xf2, 0xf5, 0xfb, 0xb6, 0x4c, 0xd9, 0xba, 0xa8, 0x7a, 0xf0, 0x8c, 0xae, 0x5c,
	0xa4, 0x10, 0x67, 0x6c, 0xc4, 0x1b, 0x71, 0x7e, 0x05, 0x32, 0xf7, 0x69, 0x1b, 0xcd, 0xe0, 0xb1,
	0x04, 0xe7, 0x83, 0xf1, 0x3f, 0x8d, 0x33, 0xa8, 0x1d, 0x9c, 0x9f, 0x7e, 0xd4, 0x21, 0xf9, 0xac,
	0x43, 0xf2, 0x5d, 0x87, 0xe4, 0xfd, 0x27, 0x5c, 0xba, 0x3b, 0x48, 0x94, 0x4f, 0xcb, 0x88, 0xc7,
	0x58, 0x88, 0x04, 0x72, 0x75, 0x5f, 0x3a, 0xf1, 0x04, 0xd1, 0x51, 0x66, 0x31, 0xc3, 0x02, 0xbd,
	0xaa, 0xa4, 0x68, 0x94, 0xa2, 0xd5, 0xd6, 0xf4, 0xe4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x59, 0x6e,
	0xe5, 0xa4, 0x60, 0x01, 0x00, 0x00,
}
